make_cmd_tests:
  normal_pipeline_args:
    args:
      all_files: null
      chromosomes: null
      genes: null
      infile: /path/to/in
      label_mapping: null
      normal_id: nid
      paramsfile: null
      project: null
      result: /path/to/out
      segment_size_threshold: '5000'
      tumour_id: tid
      types: null
    chunk: null
    output:
      cmd: python component_seed/create_case_gene_type_titan.py
      cmd_args:
            - --segment_size_threshold
            - '5000'
            - --infile
            - /path/to/in
            - --normal_id
            - nid
            - --result
            - /path/to/out
            - --tumour_id
            - tid
