make_cmd_tests:
  normal_pipeline_args:
    args:
      all_files: __OPTIONAL__
      chromosomes: null
      genes: __OPTIONAL__
      infile: __OPTIONAL__
      label_mapping: __OPTIONAL__
      normal_id: __OPTIONAL__
      paramsfile: __OPTIONAL__
      project: __OPTIONAL__
      result: __REQUIRED__
      segment_size_threshold: '5000'
      tumour_id: __OPTIONAL__
      types: __OPTIONAL__
    chunk: 'null'
    output:
      cmd: python component_seed/create_case_gene_type_titan.py
      cmd_args:
      - --label_mapping
      - __OPTIONAL__
      - --genes
      - __OPTIONAL__
      - --segment_size_threshold
      - '5000'
      - --tumour_id
      - __OPTIONAL__
      - --project
      - __OPTIONAL__
      - --normal_id
      - __OPTIONAL__
      - --result
      - __REQUIRED__
      - --all_files
      - __OPTIONAL__
      - --paramsfile
      - __OPTIONAL__
      - --infile
      - __OPTIONAL__
      - --types
      - __OPTIONAL__
